name: Unittest

on:
  push:
    branches: [ "devel" ]
  pull_request:
    branches: [ "main", "devel" ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy==0.991
        if [ -f REQUIREMENTS ]; then pip install -r REQUIREMENTS; fi
        mypy --install-types
    - name: Run mypy type check
      run: |
        mypy --strict $(git ls-files "*.py") --explicit-package-base
      working-directory: .
